In [9]:
import numpy as np

In [10]:
a = np.array([1,2,3])

In [11]:
a

array([1, 2, 3])

In [21]:
a.shape

(3,)

In [22]:
a.ndim

1

In [18]:
c = np.array([[[1,2,3], [4,5,6], 
              [7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [19]:
c.shape

(1, 3, 3)

In [20]:
c.ndim

3

In [45]:
d = np.array([[1,2,3,4,5,6,7], 
              [8,9,10,11,12,13,14]])


d[1,5]

np.int64(13)

In [46]:
# Get a specific row 

d[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [47]:
# Get specific column

d[:,2]

array([ 3, 10])

In [51]:
d[0,1:6]

array([2, 3, 4, 5, 6])

In [50]:
d[0,1:6:2]

array([2, 4, 6])

In [53]:
e = np.array([[1,2,3,4,5], 
              [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25],
             [26,27,28,29,30]])


In [54]:
e.shape

(6, 5)

In [55]:
e[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [58]:
e[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [60]:
np.full((3,5),92)

array([[92, 92, 92, 92, 92],
       [92, 92, 92, 92, 92],
       [92, 92, 92, 92, 92]])

In [61]:
# random decimal numbers
np.random.rand(4,2,4)

array([[[0.30409411, 0.20587233, 0.58466524, 0.0503851 ],
        [0.52665956, 0.27079219, 0.13825805, 0.26067235]],

       [[0.27248294, 0.39139566, 0.47704765, 0.83306466],
        [0.04601615, 0.23775756, 0.59789991, 0.0125581 ]],

       [[0.36389842, 0.72172722, 0.6955609 , 0.06648809],
        [0.76014192, 0.64560714, 0.99449166, 0.25125488]],

       [[0.079081  , 0.71678769, 0.13874786, 0.47519591],
        [0.10669794, 0.7246767 , 0.47197895, 0.51001201]]])

In [65]:
# random int numbers

np.random.randint(1,6, size=(5,6))

array([[3, 4, 1, 5, 1, 1],
       [5, 4, 1, 3, 5, 1],
       [4, 1, 1, 2, 5, 4],
       [2, 5, 3, 1, 2, 3],
       [2, 1, 1, 5, 2, 5]], dtype=int32)

In [69]:
np.random.randint(1,11, size=(3,4,2))

array([[[ 5,  3],
        [ 2,  6],
        [ 9,  9],
        [ 5,  6]],

       [[ 4,  9],
        [ 1,  2],
        [10,  6],
        [ 8,  2]],

       [[ 6,  4],
        [ 6,  3],
        [ 6,  4],
        [10,  7]]], dtype=int32)

In [70]:
np.identity

<function numpy.identity(n, dtype=None, *, like=None)>

In [85]:
j= np.ones((5,5))

j

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [93]:
f= np.zeros((3,3))

f

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [95]:
f[1,1]=9

print(f)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [100]:
# 5x5 array of ones

arr1 = np.ones((5, 5))
print(arr1)

# 3x3 array of zeros

arr2 = np.zeros((3, 3))
print(arr2)

#Its gives you '9' in the middle
# 5x5 array of ones
arr = np.ones((5, 5))

# 3x3 array of zeros in the center
arr[1:4, 1:4] = 0

# Place 9 in the center
arr[2, 2] = 9

print (arr)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
